export default function(){
  // Add your transitions here, like:
  this.transition(
    this.toRoute('index'),
    this.use('fade'),
    this.reverse('fade')
  );
  this.transition(
    this.fromRoute('sign-in'),
    this.toRoute('sign-up-p1'),
    this.use('fade'),
    this.reverse('fade')
  );
  this.transition(
    this.fromRoute('sign-in'),
    this.toRoute('user-dashboard'),
    this.use('fade')
  );
  this.transition(
    this.fromRoute('sign-up-p1'),
    this.toRoute('sign-up-p2'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.fromRoute('sign-up-p2'),
    this.toRoute('sign-up-p3'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.fromRoute('user-dashboard'),
    this.toRoute('mileage'),
    this.use('crossFade'),
    this.reverse('crossFade')
  );
  this.transition(
    this.fromRoute('user-dashboard'),
    this.toRoute('maintenance'),
    this.use('crossFade'),
    this.reverse('crossFade')
  );
  this.transition(
    this.fromRoute('user-dashboard'),
    this.toRoute('garage'),
    this.use('crossFade'),
    this.reverse('crossFade')
  );
  this.transition(
    this.fromRoute('mileage'),
    this.toRoute('maintenance'),
    this.use('crossFade'),
    this.reverse('crossFade')
  );
  this.transition(
    this.fromRoute('mileage'),
    this.toRoute('garage'),
    this.use('crossFade'),
    this.reverse('crossFade')
  );
  this.transition(
    this.fromRoute('garage'),
    this.toRoute('maintenance'),
    this.use('crossFade'),
    this.reverse('crossFade')
  );
  this.transition(
    this.toRoute('change-password'),
    this.use('crossFade'),
    this.reverse('crossFade')
  );
  this.transition(
    this.toRoute('create-a-new-mileage-record'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('editmileage'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('create-a-new-maintenance-record'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('editmaintenance'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('create-a-new-car-record'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('edit-car'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
}
